// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AddToCartArea from "./islands/AddToCartArea.tsx";
import * as $AddToCartButton_linx from "./islands/AddToCartButton/linx.tsx";
import * as $AddToCartButton_nuvemshop from "./islands/AddToCartButton/nuvemshop.tsx";
import * as $AddToCartButton_shopify from "./islands/AddToCartButton/shopify.tsx";
import * as $AddToCartButton_vnda from "./islands/AddToCartButton/vnda.tsx";
import * as $AddToCartButton_vtex from "./islands/AddToCartButton/vtex.tsx";
import * as $AddToCartButton_wake from "./islands/AddToCartButton/wake.tsx";
import * as $BannerCarouselJS from "./islands/BannerCarouselJS.tsx";
import * as $CartItem from "./islands/CartItem.tsx";
import * as $CouponPopup from "./islands/CouponPopup.tsx";
import * as $Header_Buttons from "./islands/Header/Buttons.tsx";
import * as $Header_Cart_Cart from "./islands/Header/Cart/Cart.tsx";
import * as $Header_Cart_common from "./islands/Header/Cart/common.tsx";
import * as $Header_Cart_vtex from "./islands/Header/Cart/vtex.tsx";
import * as $Header_Drawers from "./islands/Header/Drawers.tsx";
import * as $Header_MyAccount from "./islands/Header/MyAccount.tsx";
import * as $Header_Searchbar from "./islands/Header/Searchbar.tsx";
import * as $MicroHeaderSetup from "./islands/MicroHeaderSetup.tsx";
import * as $NavbarWrapper from "./islands/NavbarWrapper.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $OutOfStock from "./islands/OutOfStock.tsx";
import * as $PixPrice from "./islands/PixPrice.tsx";
import * as $PriceRange from "./islands/PriceRange.tsx";
import * as $ProductImageZoom from "./islands/ProductImageZoom.tsx";
import * as $Product_Benefits from "./islands/Product/Benefits.tsx";
import * as $Product_ProductCard from "./islands/Product/ProductCard.tsx";
import * as $Product_ProductSimilars from "./islands/Product/ProductSimilars.tsx";
import * as $Product_ProductStarCard from "./islands/Product/ProductStarCard.tsx";
import * as $Product_ProductStars from "./islands/Product/ProductStars.tsx";
import * as $Product_SellingPrice from "./islands/Product/SellingPrice.tsx";
import * as $Product_Trustvox from "./islands/Product/Trustvox.tsx";
import * as $Radio from "./islands/Radio.tsx";
import * as $SearchControls from "./islands/SearchControls.tsx";
import * as $ShippingSimulation from "./islands/ShippingSimulation.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import * as $Subscription from "./islands/Subscription.tsx";
import * as $SubscriptionModal from "./islands/SubscriptionModal.tsx";
import * as $VideoModal_Button from "./islands/VideoModal/Button.tsx";
import * as $VideoModal_Modal from "./islands/VideoModal/Modal.tsx";
import * as $WishlistButton_vtex from "./islands/WishlistButton/vtex.tsx";
import * as $WishlistButton_wake from "./islands/WishlistButton/wake.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AddToCartArea.tsx": $AddToCartArea,
    "./islands/AddToCartButton/linx.tsx": $AddToCartButton_linx,
    "./islands/AddToCartButton/nuvemshop.tsx": $AddToCartButton_nuvemshop,
    "./islands/AddToCartButton/shopify.tsx": $AddToCartButton_shopify,
    "./islands/AddToCartButton/vnda.tsx": $AddToCartButton_vnda,
    "./islands/AddToCartButton/vtex.tsx": $AddToCartButton_vtex,
    "./islands/AddToCartButton/wake.tsx": $AddToCartButton_wake,
    "./islands/BannerCarouselJS.tsx": $BannerCarouselJS,
    "./islands/CartItem.tsx": $CartItem,
    "./islands/CouponPopup.tsx": $CouponPopup,
    "./islands/Header/Buttons.tsx": $Header_Buttons,
    "./islands/Header/Cart/Cart.tsx": $Header_Cart_Cart,
    "./islands/Header/Cart/common.tsx": $Header_Cart_common,
    "./islands/Header/Cart/vtex.tsx": $Header_Cart_vtex,
    "./islands/Header/Drawers.tsx": $Header_Drawers,
    "./islands/Header/MyAccount.tsx": $Header_MyAccount,
    "./islands/Header/Searchbar.tsx": $Header_Searchbar,
    "./islands/MicroHeaderSetup.tsx": $MicroHeaderSetup,
    "./islands/NavbarWrapper.tsx": $NavbarWrapper,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/OutOfStock.tsx": $OutOfStock,
    "./islands/PixPrice.tsx": $PixPrice,
    "./islands/PriceRange.tsx": $PriceRange,
    "./islands/ProductImageZoom.tsx": $ProductImageZoom,
    "./islands/Product/Benefits.tsx": $Product_Benefits,
    "./islands/Product/ProductCard.tsx": $Product_ProductCard,
    "./islands/Product/ProductSimilars.tsx": $Product_ProductSimilars,
    "./islands/Product/ProductStarCard.tsx": $Product_ProductStarCard,
    "./islands/Product/ProductStars.tsx": $Product_ProductStars,
    "./islands/Product/SellingPrice.tsx": $Product_SellingPrice,
    "./islands/Product/Trustvox.tsx": $Product_Trustvox,
    "./islands/Radio.tsx": $Radio,
    "./islands/SearchControls.tsx": $SearchControls,
    "./islands/ShippingSimulation.tsx": $ShippingSimulation,
    "./islands/SliderJS.tsx": $SliderJS,
    "./islands/Subscription.tsx": $Subscription,
    "./islands/SubscriptionModal.tsx": $SubscriptionModal,
    "./islands/VideoModal/Button.tsx": $VideoModal_Button,
    "./islands/VideoModal/Modal.tsx": $VideoModal_Modal,
    "./islands/WishlistButton/vtex.tsx": $WishlistButton_vtex,
    "./islands/WishlistButton/wake.tsx": $WishlistButton_wake,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
