// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$0 from "./loaders/CustomPLPTitle.ts";
import * as $$$1 from "./loaders/PLPSectionsSEO.ts";
import * as $$$$$$0 from "./sections/Animation/Animation.tsx";
import * as $$$$$$3 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$4 from "./sections/Category/CategoryGrid.tsx";
import * as $$$$$$5 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$1 from "./sections/CategoryDescription/CategoryInfoCard.tsx";
import * as $$$$$$2 from "./sections/CategoryDescription/CategoryOnlyText.tsx";
import * as $$$$$$6 from "./sections/Content/Benefits.tsx";
import * as $$$$$$7 from "./sections/Content/BlogPosts.tsx";
import * as $$$$$$8 from "./sections/Content/CallToAction.tsx";
import * as $$$$$$9 from "./sections/Content/CardsSlider.tsx";
import * as $$$$$$10 from "./sections/Content/CardsWithCta.tsx";
import * as $$$$$$11 from "./sections/Content/CardsWithImageCta.tsx";
import * as $$$$$$12 from "./sections/Content/DescriptionWithCta.tsx";
import * as $$$$$$13 from "./sections/Content/Faq.tsx";
import * as $$$$$$14 from "./sections/Content/Features.tsx";
import * as $$$$$$15 from "./sections/Content/Hero.tsx";
import * as $$$$$$16 from "./sections/Content/HighlightsBanner.tsx";
import * as $$$$$$17 from "./sections/Content/ImageSection.tsx";
import * as $$$$$$18 from "./sections/Content/InfluencersCarousel.tsx";
import * as $$$$$$19 from "./sections/Content/Logos.tsx";
import * as $$$$$$20 from "./sections/Content/RichText.tsx";
import * as $$$$$$21 from "./sections/Content/Table.tsx";
import * as $$$$$$22 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$23 from "./sections/Footer/Footer.tsx";
import * as $$$$$$24 from "./sections/Gallery.tsx";
import * as $$$$$$25 from "./sections/Header/Header.tsx";
import * as $$$$$$26 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$27 from "./sections/Images/BannerInfo.tsx";
import * as $$$$$$28 from "./sections/Images/BannerInfoContainer.tsx";
import * as $$$$$$29 from "./sections/Images/BannerInfoWithItems.tsx";
import * as $$$$$$30 from "./sections/Images/Carousel.tsx";
import * as $$$$$$31 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$32 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$33 from "./sections/Layout/Container.tsx";
import * as $$$$$$34 from "./sections/Layout/Flex.tsx";
import * as $$$$$$35 from "./sections/Layout/Grid.tsx";
import * as $$$$$$36 from "./sections/Layout/GridItem.tsx";
import * as $$$$$$37 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$38 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$39 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$40 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$41 from "./sections/Miscellaneous/FloatingButtons.tsx.tsx";
import * as $$$$$$42 from "./sections/Miscellaneous/Slide.tsx";
import * as $$$$$$43 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$52 from "./sections/Product/Description.tsx";
import * as $$$$$$53 from "./sections/Product/ImageGalleryFrontBack.tsx";
import * as $$$$$$54 from "./sections/Product/ImageGallerySlider.tsx";
import * as $$$$$$55 from "./sections/Product/NotFound.tsx";
import * as $$$$$$56 from "./sections/Product/NotFoundChallenge.tsx";
import * as $$$$$$57 from "./sections/Product/ProductInfo.tsx";
import * as $$$$$$58 from "./sections/Product/ProductMain.tsx";
import * as $$$$$$59 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$60 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$61 from "./sections/Product/ShelfWithImage.tsx";
import * as $$$$$$62 from "./sections/Product/SubscriptionModal.tsx";
import * as $$$$$$63 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$44 from "./sections/ProductDescription/ProductBenefits.tsx";
import * as $$$$$$45 from "./sections/ProductDescription/ProductComparison.tsx";
import * as $$$$$$46 from "./sections/ProductDescription/ProductContainer.tsx";
import * as $$$$$$47 from "./sections/ProductDescription/ProductGallery.tsx";
import * as $$$$$$48 from "./sections/ProductDescription/ProductInfoCard.tsx";
import * as $$$$$$49 from "./sections/ProductDescription/ProductNutritionalHighlights.tsx";
import * as $$$$$$50 from "./sections/ProductDescription/ProductNutritionalTable.tsx";
import * as $$$$$$51 from "./sections/ProductDescription/ProductSpace.tsx";
import * as $$$$$$64 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$65 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$66 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "deco-sites/true-source/loaders/CustomPLPTitle.ts": $$$0,
    "deco-sites/true-source/loaders/PLPSectionsSEO.ts": $$$1,
  },
  "sections": {
    "deco-sites/true-source/sections/Animation/Animation.tsx": $$$$$$0,
    "deco-sites/true-source/sections/Category/CategoryBanner.tsx": $$$$$$3,
    "deco-sites/true-source/sections/Category/CategoryGrid.tsx": $$$$$$4,
    "deco-sites/true-source/sections/Category/CategoryList.tsx": $$$$$$5,
    "deco-sites/true-source/sections/CategoryDescription/CategoryInfoCard.tsx":
      $$$$$$1,
    "deco-sites/true-source/sections/CategoryDescription/CategoryOnlyText.tsx":
      $$$$$$2,
    "deco-sites/true-source/sections/Content/Benefits.tsx": $$$$$$6,
    "deco-sites/true-source/sections/Content/BlogPosts.tsx": $$$$$$7,
    "deco-sites/true-source/sections/Content/CallToAction.tsx": $$$$$$8,
    "deco-sites/true-source/sections/Content/CardsSlider.tsx": $$$$$$9,
    "deco-sites/true-source/sections/Content/CardsWithCta.tsx": $$$$$$10,
    "deco-sites/true-source/sections/Content/CardsWithImageCta.tsx": $$$$$$11,
    "deco-sites/true-source/sections/Content/DescriptionWithCta.tsx": $$$$$$12,
    "deco-sites/true-source/sections/Content/Faq.tsx": $$$$$$13,
    "deco-sites/true-source/sections/Content/Features.tsx": $$$$$$14,
    "deco-sites/true-source/sections/Content/Hero.tsx": $$$$$$15,
    "deco-sites/true-source/sections/Content/HighlightsBanner.tsx": $$$$$$16,
    "deco-sites/true-source/sections/Content/ImageSection.tsx": $$$$$$17,
    "deco-sites/true-source/sections/Content/InfluencersCarousel.tsx": $$$$$$18,
    "deco-sites/true-source/sections/Content/Logos.tsx": $$$$$$19,
    "deco-sites/true-source/sections/Content/RichText.tsx": $$$$$$20,
    "deco-sites/true-source/sections/Content/Table.tsx": $$$$$$21,
    "deco-sites/true-source/sections/Content/Testimonials.tsx": $$$$$$22,
    "deco-sites/true-source/sections/Footer/Footer.tsx": $$$$$$23,
    "deco-sites/true-source/sections/Gallery.tsx": $$$$$$24,
    "deco-sites/true-source/sections/Header/Header.tsx": $$$$$$25,
    "deco-sites/true-source/sections/Images/BannerGrid.tsx": $$$$$$26,
    "deco-sites/true-source/sections/Images/BannerInfo.tsx": $$$$$$27,
    "deco-sites/true-source/sections/Images/BannerInfoContainer.tsx": $$$$$$28,
    "deco-sites/true-source/sections/Images/BannerInfoWithItems.tsx": $$$$$$29,
    "deco-sites/true-source/sections/Images/Carousel.tsx": $$$$$$30,
    "deco-sites/true-source/sections/Images/ImageGallery.tsx": $$$$$$31,
    "deco-sites/true-source/sections/Images/ShoppableBanner.tsx": $$$$$$32,
    "deco-sites/true-source/sections/Layout/Container.tsx": $$$$$$33,
    "deco-sites/true-source/sections/Layout/Flex.tsx": $$$$$$34,
    "deco-sites/true-source/sections/Layout/Grid.tsx": $$$$$$35,
    "deco-sites/true-source/sections/Layout/GridItem.tsx": $$$$$$36,
    "deco-sites/true-source/sections/Links/LinkTree.tsx": $$$$$$37,
    "deco-sites/true-source/sections/Links/Shortcuts.tsx": $$$$$$38,
    "deco-sites/true-source/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$39,
    "deco-sites/true-source/sections/Miscellaneous/CookieConsent.tsx": $$$$$$40,
    "deco-sites/true-source/sections/Miscellaneous/FloatingButtons.tsx.tsx":
      $$$$$$41,
    "deco-sites/true-source/sections/Miscellaneous/Slide.tsx": $$$$$$42,
    "deco-sites/true-source/sections/Newsletter/Newsletter.tsx": $$$$$$43,
    "deco-sites/true-source/sections/Product/Description.tsx": $$$$$$52,
    "deco-sites/true-source/sections/Product/ImageGalleryFrontBack.tsx":
      $$$$$$53,
    "deco-sites/true-source/sections/Product/ImageGallerySlider.tsx": $$$$$$54,
    "deco-sites/true-source/sections/Product/NotFound.tsx": $$$$$$55,
    "deco-sites/true-source/sections/Product/NotFoundChallenge.tsx": $$$$$$56,
    "deco-sites/true-source/sections/Product/ProductInfo.tsx": $$$$$$57,
    "deco-sites/true-source/sections/Product/ProductMain.tsx": $$$$$$58,
    "deco-sites/true-source/sections/Product/ProductShelf.tsx": $$$$$$59,
    "deco-sites/true-source/sections/Product/SearchResult.tsx": $$$$$$60,
    "deco-sites/true-source/sections/Product/ShelfWithImage.tsx": $$$$$$61,
    "deco-sites/true-source/sections/Product/SubscriptionModal.tsx": $$$$$$62,
    "deco-sites/true-source/sections/Product/Wishlist.tsx": $$$$$$63,
    "deco-sites/true-source/sections/ProductDescription/ProductBenefits.tsx":
      $$$$$$44,
    "deco-sites/true-source/sections/ProductDescription/ProductComparison.tsx":
      $$$$$$45,
    "deco-sites/true-source/sections/ProductDescription/ProductContainer.tsx":
      $$$$$$46,
    "deco-sites/true-source/sections/ProductDescription/ProductGallery.tsx":
      $$$$$$47,
    "deco-sites/true-source/sections/ProductDescription/ProductInfoCard.tsx":
      $$$$$$48,
    "deco-sites/true-source/sections/ProductDescription/ProductNutritionalHighlights.tsx":
      $$$$$$49,
    "deco-sites/true-source/sections/ProductDescription/ProductNutritionalTable.tsx":
      $$$$$$50,
    "deco-sites/true-source/sections/ProductDescription/ProductSpace.tsx":
      $$$$$$51,
    "deco-sites/true-source/sections/Social/InstagramPosts.tsx": $$$$$$64,
    "deco-sites/true-source/sections/Social/WhatsApp.tsx": $$$$$$65,
    "deco-sites/true-source/sections/Theme/Theme.tsx": $$$$$$66,
  },
  "apps": {
    "deco-sites/true-source/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/true-source/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/true-source",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
