// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$2 from "./loaders/availableIcons.ts";
import * as $$$3 from "./loaders/centralNavigation.ts";
import * as $$$0 from "./loaders/CustomPLPTitle.ts";
import * as $$$1 from "./loaders/PLPSectionsSEO.ts";
import * as $$$$$$0 from "./sections/Animation/Animation.tsx";
import * as $$$$$$3 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$4 from "./sections/Category/CategoryCarousel.tsx";
import * as $$$$$$5 from "./sections/Category/CategoryGrid.tsx";
import * as $$$$$$6 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$1 from "./sections/CategoryDescription/CategoryInfoCard.tsx";
import * as $$$$$$2 from "./sections/CategoryDescription/CategoryOnlyText.tsx";
import * as $$$$$$8 from "./sections/CentralAtendimento/BannerCabecalho.tsx";
import * as $$$$$$7 from "./sections/CentralAtendimento/BannerCTA.tsx";
import * as $$$$$$9 from "./sections/CentralAtendimento/CardEmail.tsx";
import * as $$$$$$10 from "./sections/CentralAtendimento/CardEmailLinked.tsx";
import * as $$$$$$11 from "./sections/CentralAtendimento/CardNumbered.tsx";
import * as $$$$$$12 from "./sections/CentralAtendimento/CardNumberedSection.tsx";
import * as $$$$$$13 from "./sections/CentralAtendimento/CardPhone.tsx";
import * as $$$$$$14 from "./sections/CentralAtendimento/CardRichText.tsx";
import * as $$$$$$15 from "./sections/CentralAtendimento/CardsTitle.tsx";
import * as $$$$$$16 from "./sections/CentralAtendimento/CardsTitleSimple.tsx";
import * as $$$$$$17 from "./sections/CentralAtendimento/CardsTitleSimpleH3.tsx";
import * as $$$$$$18 from "./sections/CentralAtendimento/EmptySection.tsx";
import * as $$$$$$19 from "./sections/CentralAtendimento/Faq.tsx";
import * as $$$$$$20 from "./sections/CentralAtendimento/FormCard.tsx";
import * as $$$$$$21 from "./sections/CentralAtendimento/InfoCard.tsx";
import * as $$$$$$22 from "./sections/CentralAtendimento/InfoCardSection.tsx";
import * as $$$$$$23 from "./sections/CentralAtendimento/NavegacaoCentralAtendimento.tsx";
import * as $$$$$$24 from "./sections/CentralAtendimento/NavigationMenu.tsx";
import * as $$$$$$25 from "./sections/CentralAtendimento/NavigationPage.tsx";
import * as $$$$$$26 from "./sections/CentralAtendimento/TextInput.tsx";
import * as $$$$$$27 from "./sections/Content/Benefits.tsx";
import * as $$$$$$28 from "./sections/Content/BlogPosts.tsx";
import * as $$$$$$29 from "./sections/Content/CallToAction.tsx";
import * as $$$$$$30 from "./sections/Content/CardsSlider.tsx";
import * as $$$$$$31 from "./sections/Content/CardsWithCta.tsx";
import * as $$$$$$32 from "./sections/Content/CardsWithImageCta.tsx";
import * as $$$$$$33 from "./sections/Content/CouponPopup.tsx";
import * as $$$$$$34 from "./sections/Content/DescriptionWithCta.tsx";
import * as $$$$$$35 from "./sections/Content/Faq.tsx";
import * as $$$$$$36 from "./sections/Content/Features.tsx";
import * as $$$$$$37 from "./sections/Content/FormLojistas.tsx";
import * as $$$$$$38 from "./sections/Content/FormProfissionais.tsx";
import * as $$$$$$39 from "./sections/Content/Hero.tsx";
import * as $$$$$$40 from "./sections/Content/HighlightsBanner.tsx";
import * as $$$$$$41 from "./sections/Content/ImageSection.tsx";
import * as $$$$$$42 from "./sections/Content/InfluencersCarousel.tsx";
import * as $$$$$$43 from "./sections/Content/Logos.tsx";
import * as $$$$$$44 from "./sections/Content/RichText.tsx";
import * as $$$$$$45 from "./sections/Content/SubscriptionPopup.tsx";
import * as $$$$$$46 from "./sections/Content/Table.tsx";
import * as $$$$$$47 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$48 from "./sections/Content/Timeline.tsx";
import * as $$$$$$49 from "./sections/Content/VideoModal.tsx";
import * as $$$$$$50 from "./sections/Footer/Footer.tsx";
import * as $$$$$$51 from "./sections/Gallery.tsx";
import * as $$$$$$52 from "./sections/Header/Header.tsx";
import * as $$$$$$53 from "./sections/Images/AccordionWithImages.tsx";
import * as $$$$$$54 from "./sections/Images/BannerImage.tsx";
import * as $$$$$$55 from "./sections/Images/BannerInfo.tsx";
import * as $$$$$$56 from "./sections/Images/BannerInfoContainer.tsx";
import * as $$$$$$57 from "./sections/Images/BannerInfoWithDivider.tsx";
import * as $$$$$$58 from "./sections/Images/BannerInfoWithItems.tsx";
import * as $$$$$$59 from "./sections/Images/Carousel.tsx";
import * as $$$$$$60 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$61 from "./sections/Images/ImageGrid.tsx";
import * as $$$$$$62 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$63 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$64 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$65 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$66 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$67 from "./sections/Miscellaneous/FloatingButtons.tsx";
import * as $$$$$$68 from "./sections/Miscellaneous/ProxyIframe.tsx";
import * as $$$$$$69 from "./sections/Miscellaneous/Slide.tsx";
import * as $$$$$$70 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$81 from "./sections/Product/Description.tsx";
import * as $$$$$$82 from "./sections/Product/ImageGalleryFrontBack.tsx";
import * as $$$$$$83 from "./sections/Product/ImageGallerySlider.tsx";
import * as $$$$$$84 from "./sections/Product/NotFound.tsx";
import * as $$$$$$85 from "./sections/Product/NotFoundChallenge.tsx";
import * as $$$$$$86 from "./sections/Product/ProductInfo.tsx";
import * as $$$$$$87 from "./sections/Product/ProductMain.tsx";
import * as $$$$$$88 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$89 from "./sections/Product/ProductShelfWithImage.tsx";
import * as $$$$$$90 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$91 from "./sections/Product/SubscriptionModal.tsx";
import * as $$$$$$92 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$71 from "./sections/ProductDescription/ProductBenefits.tsx";
import * as $$$$$$72 from "./sections/ProductDescription/ProductComparison.tsx";
import * as $$$$$$73 from "./sections/ProductDescription/ProductContainer.tsx";
import * as $$$$$$74 from "./sections/ProductDescription/ProductGallery.tsx";
import * as $$$$$$75 from "./sections/ProductDescription/ProductInfoCard.tsx";
import * as $$$$$$76 from "./sections/ProductDescription/ProductInfoCard1WithBackground.tsx";
import * as $$$$$$77 from "./sections/ProductDescription/ProductNutritionalHighlights.tsx";
import * as $$$$$$78 from "./sections/ProductDescription/ProductNutritionalTable.tsx";
import * as $$$$$$79 from "./sections/ProductDescription/ProductNutritionalTable2.tsx";
import * as $$$$$$80 from "./sections/ProductDescription/ProductSpace.tsx";
import * as $$$$$$93 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$94 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "deco-sites/true-source/loaders/availableIcons.ts": $$$2,
    "deco-sites/true-source/loaders/centralNavigation.ts": $$$3,
    "deco-sites/true-source/loaders/CustomPLPTitle.ts": $$$0,
    "deco-sites/true-source/loaders/PLPSectionsSEO.ts": $$$1,
  },
  "sections": {
    "deco-sites/true-source/sections/Animation/Animation.tsx": $$$$$$0,
    "deco-sites/true-source/sections/Category/CategoryBanner.tsx": $$$$$$3,
    "deco-sites/true-source/sections/Category/CategoryCarousel.tsx": $$$$$$4,
    "deco-sites/true-source/sections/Category/CategoryGrid.tsx": $$$$$$5,
    "deco-sites/true-source/sections/Category/CategoryList.tsx": $$$$$$6,
    "deco-sites/true-source/sections/CategoryDescription/CategoryInfoCard.tsx":
      $$$$$$1,
    "deco-sites/true-source/sections/CategoryDescription/CategoryOnlyText.tsx":
      $$$$$$2,
    "deco-sites/true-source/sections/CentralAtendimento/BannerCabecalho.tsx":
      $$$$$$8,
    "deco-sites/true-source/sections/CentralAtendimento/BannerCTA.tsx": $$$$$$7,
    "deco-sites/true-source/sections/CentralAtendimento/CardEmail.tsx": $$$$$$9,
    "deco-sites/true-source/sections/CentralAtendimento/CardEmailLinked.tsx":
      $$$$$$10,
    "deco-sites/true-source/sections/CentralAtendimento/CardNumbered.tsx":
      $$$$$$11,
    "deco-sites/true-source/sections/CentralAtendimento/CardNumberedSection.tsx":
      $$$$$$12,
    "deco-sites/true-source/sections/CentralAtendimento/CardPhone.tsx":
      $$$$$$13,
    "deco-sites/true-source/sections/CentralAtendimento/CardRichText.tsx":
      $$$$$$14,
    "deco-sites/true-source/sections/CentralAtendimento/CardsTitle.tsx":
      $$$$$$15,
    "deco-sites/true-source/sections/CentralAtendimento/CardsTitleSimple.tsx":
      $$$$$$16,
    "deco-sites/true-source/sections/CentralAtendimento/CardsTitleSimpleH3.tsx":
      $$$$$$17,
    "deco-sites/true-source/sections/CentralAtendimento/EmptySection.tsx":
      $$$$$$18,
    "deco-sites/true-source/sections/CentralAtendimento/Faq.tsx": $$$$$$19,
    "deco-sites/true-source/sections/CentralAtendimento/FormCard.tsx": $$$$$$20,
    "deco-sites/true-source/sections/CentralAtendimento/InfoCard.tsx": $$$$$$21,
    "deco-sites/true-source/sections/CentralAtendimento/InfoCardSection.tsx":
      $$$$$$22,
    "deco-sites/true-source/sections/CentralAtendimento/NavegacaoCentralAtendimento.tsx":
      $$$$$$23,
    "deco-sites/true-source/sections/CentralAtendimento/NavigationMenu.tsx":
      $$$$$$24,
    "deco-sites/true-source/sections/CentralAtendimento/NavigationPage.tsx":
      $$$$$$25,
    "deco-sites/true-source/sections/CentralAtendimento/TextInput.tsx":
      $$$$$$26,
    "deco-sites/true-source/sections/Content/Benefits.tsx": $$$$$$27,
    "deco-sites/true-source/sections/Content/BlogPosts.tsx": $$$$$$28,
    "deco-sites/true-source/sections/Content/CallToAction.tsx": $$$$$$29,
    "deco-sites/true-source/sections/Content/CardsSlider.tsx": $$$$$$30,
    "deco-sites/true-source/sections/Content/CardsWithCta.tsx": $$$$$$31,
    "deco-sites/true-source/sections/Content/CardsWithImageCta.tsx": $$$$$$32,
    "deco-sites/true-source/sections/Content/CouponPopup.tsx": $$$$$$33,
    "deco-sites/true-source/sections/Content/DescriptionWithCta.tsx": $$$$$$34,
    "deco-sites/true-source/sections/Content/Faq.tsx": $$$$$$35,
    "deco-sites/true-source/sections/Content/Features.tsx": $$$$$$36,
    "deco-sites/true-source/sections/Content/FormLojistas.tsx": $$$$$$37,
    "deco-sites/true-source/sections/Content/FormProfissionais.tsx": $$$$$$38,
    "deco-sites/true-source/sections/Content/Hero.tsx": $$$$$$39,
    "deco-sites/true-source/sections/Content/HighlightsBanner.tsx": $$$$$$40,
    "deco-sites/true-source/sections/Content/ImageSection.tsx": $$$$$$41,
    "deco-sites/true-source/sections/Content/InfluencersCarousel.tsx": $$$$$$42,
    "deco-sites/true-source/sections/Content/Logos.tsx": $$$$$$43,
    "deco-sites/true-source/sections/Content/RichText.tsx": $$$$$$44,
    "deco-sites/true-source/sections/Content/SubscriptionPopup.tsx": $$$$$$45,
    "deco-sites/true-source/sections/Content/Table.tsx": $$$$$$46,
    "deco-sites/true-source/sections/Content/Testimonials.tsx": $$$$$$47,
    "deco-sites/true-source/sections/Content/Timeline.tsx": $$$$$$48,
    "deco-sites/true-source/sections/Content/VideoModal.tsx": $$$$$$49,
    "deco-sites/true-source/sections/Footer/Footer.tsx": $$$$$$50,
    "deco-sites/true-source/sections/Gallery.tsx": $$$$$$51,
    "deco-sites/true-source/sections/Header/Header.tsx": $$$$$$52,
    "deco-sites/true-source/sections/Images/AccordionWithImages.tsx": $$$$$$53,
    "deco-sites/true-source/sections/Images/BannerImage.tsx": $$$$$$54,
    "deco-sites/true-source/sections/Images/BannerInfo.tsx": $$$$$$55,
    "deco-sites/true-source/sections/Images/BannerInfoContainer.tsx": $$$$$$56,
    "deco-sites/true-source/sections/Images/BannerInfoWithDivider.tsx":
      $$$$$$57,
    "deco-sites/true-source/sections/Images/BannerInfoWithItems.tsx": $$$$$$58,
    "deco-sites/true-source/sections/Images/Carousel.tsx": $$$$$$59,
    "deco-sites/true-source/sections/Images/ImageGallery.tsx": $$$$$$60,
    "deco-sites/true-source/sections/Images/ImageGrid.tsx": $$$$$$61,
    "deco-sites/true-source/sections/Images/ShoppableBanner.tsx": $$$$$$62,
    "deco-sites/true-source/sections/Links/LinkTree.tsx": $$$$$$63,
    "deco-sites/true-source/sections/Links/Shortcuts.tsx": $$$$$$64,
    "deco-sites/true-source/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$65,
    "deco-sites/true-source/sections/Miscellaneous/CookieConsent.tsx": $$$$$$66,
    "deco-sites/true-source/sections/Miscellaneous/FloatingButtons.tsx":
      $$$$$$67,
    "deco-sites/true-source/sections/Miscellaneous/ProxyIframe.tsx": $$$$$$68,
    "deco-sites/true-source/sections/Miscellaneous/Slide.tsx": $$$$$$69,
    "deco-sites/true-source/sections/Newsletter/Newsletter.tsx": $$$$$$70,
    "deco-sites/true-source/sections/Product/Description.tsx": $$$$$$81,
    "deco-sites/true-source/sections/Product/ImageGalleryFrontBack.tsx":
      $$$$$$82,
    "deco-sites/true-source/sections/Product/ImageGallerySlider.tsx": $$$$$$83,
    "deco-sites/true-source/sections/Product/NotFound.tsx": $$$$$$84,
    "deco-sites/true-source/sections/Product/NotFoundChallenge.tsx": $$$$$$85,
    "deco-sites/true-source/sections/Product/ProductInfo.tsx": $$$$$$86,
    "deco-sites/true-source/sections/Product/ProductMain.tsx": $$$$$$87,
    "deco-sites/true-source/sections/Product/ProductShelf.tsx": $$$$$$88,
    "deco-sites/true-source/sections/Product/ProductShelfWithImage.tsx":
      $$$$$$89,
    "deco-sites/true-source/sections/Product/SearchResult.tsx": $$$$$$90,
    "deco-sites/true-source/sections/Product/SubscriptionModal.tsx": $$$$$$91,
    "deco-sites/true-source/sections/Product/Wishlist.tsx": $$$$$$92,
    "deco-sites/true-source/sections/ProductDescription/ProductBenefits.tsx":
      $$$$$$71,
    "deco-sites/true-source/sections/ProductDescription/ProductComparison.tsx":
      $$$$$$72,
    "deco-sites/true-source/sections/ProductDescription/ProductContainer.tsx":
      $$$$$$73,
    "deco-sites/true-source/sections/ProductDescription/ProductGallery.tsx":
      $$$$$$74,
    "deco-sites/true-source/sections/ProductDescription/ProductInfoCard.tsx":
      $$$$$$75,
    "deco-sites/true-source/sections/ProductDescription/ProductInfoCard1WithBackground.tsx":
      $$$$$$76,
    "deco-sites/true-source/sections/ProductDescription/ProductNutritionalHighlights.tsx":
      $$$$$$77,
    "deco-sites/true-source/sections/ProductDescription/ProductNutritionalTable.tsx":
      $$$$$$78,
    "deco-sites/true-source/sections/ProductDescription/ProductNutritionalTable2.tsx":
      $$$$$$79,
    "deco-sites/true-source/sections/ProductDescription/ProductSpace.tsx":
      $$$$$$80,
    "deco-sites/true-source/sections/Social/WhatsApp.tsx": $$$$$$93,
    "deco-sites/true-source/sections/Theme/Theme.tsx": $$$$$$94,
  },
  "apps": {
    "deco-sites/true-source/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/true-source/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/true-source",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
